"use client";

import Link from "next/link";
import {BrandLogo} from "@/components/BrandLogo";
import {useEffect,useMemo,useState} from "react";
import {lmsApi} from "@/lib/api";
import type {Bootstrap,Pathway} from "@/lib/types";

const nav=[["⌂","Dashboard",""],["▧","My Courses","courses"],["♙","My Cohorts","cohorts"],["♙","Students","students"],["▣","Assessments","assessments"],["▣","Resources","resources"],["▦","Calendar","calendar"],["✉","Messages","messages"],["♡","Support","support"],["▥","Reports","reports"],["⚙","Settings","settings"]] as const;

export function InstructorPortal({section=""}:{section?:string}){
  const [data,setData]=useState<Bootstrap|null>(null);
  const [toast,setToast]=useState("");
  useEffect(()=>{lmsApi.bootstrap().then(setData)},[]);
  const assigned=useMemo(()=>data?.curriculum.paths.slice(1,5)||[],[data]);
  const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
  if(!data)return <main className="institution-loading">Preparing instructor workspace…</main>;
  return <main className="institution-portal instructor-portal">
    <aside className="institution-sidebar"><BrandLogo light className="institution-logo" /><nav>{nav.map(([icon,title,slug])=><Link className={section===slug?"active":""} href={`/dashboard/instructor${slug?"/"+slug:""}`} key={title}><span>{icon}</span>{title}</Link>)}</nav><div className="institution-identity"><span>♧</span><strong>Make a bigger impact.<small>Teach skills. Change lives.</small></strong></div></aside>
    <div className="institution-main"><header className="institution-topbar"><label>⌕<input placeholder="Search learners, courses, or resources…"/></label><button>♧<i>3</i></button><button className="institution-user"><span>J</span><strong>Jamie Carter<small>Instructor</small></strong>⌄</button></header>{section?<InstructorInterior section={section} paths={assigned} notify={notify}/>:<InstructorHome paths={assigned}/>}</div>
    <div className={`portal-toast ${toast?"show":""}`}>{toast}</div>
  </main>
}

function InstructorHome({paths}:{paths:Pathway[]}){
  return <section className="institution-dashboard instructor-dashboard"><header className="instructor-welcome"><div><small>INSTRUCTOR DASHBOARD</small><h1>Good morning, Jamie!</h1><p>Here’s your teaching overview for today. Keep supporting learners and building their future.</p></div></header><div className="institution-kpis">{[["◇","My Courses",String(paths.length),"Active courses"],["♙","My Students","48","Total enrolled"],["▣","Pending Assessments","12","To grade"],["▦","Upcoming Sessions","3","Live or scheduled"]].map(([icon,title,value,caption])=><article key={title}><span>{icon}</span><div><small>{title}</small><strong>{value}</strong><p>{caption}</p></div></article>)}</div><div className="instructor-home-grid"><section className="institution-card"><header><h2>Today’s Schedule</h2><Link href="/dashboard/instructor/calendar">View Full Calendar</Link></header>{paths.map((p,i)=><p className="session-row" key={p.code}><i/><span><b>{9+i*2}:00 AM – {10+i*2}:00 AM</b><strong>{p.code}: {p.title}</strong><small>Cohort {String.fromCharCode(65+i)} · {8+i*2} students</small></span><Link href="/dashboard/instructor/calendar">{i%2?"View Details":"Join Session"}</Link></p>)}</section><section className="institution-card"><header><h2>My Courses</h2><Link href="/dashboard/instructor/courses">View All Courses</Link></header>{paths.map((p,i)=><Link className="assigned-course" href="/dashboard/instructor/courses" key={p.code}><img src={["/leashed-assets/program-groomer.webp","/leashed-assets/program-business.webp","/leashed-assets/program-cat.webp","/leashed-assets/program-sitter.webp"][i]} alt=""/><span><strong>{p.code}: {p.title}</strong><progress max="100" value={78-i*14}/><small>{78-i*14}% complete</small></span><b>{8+i*2} students</b></Link>)}</section><aside className="institution-card institution-actions"><h2>Quick Actions</h2><Link href="/dashboard/instructor/messages">✉ Create Announcement</Link><Link href="/dashboard/instructor/resources">↑ Upload Resources</Link><Link href="/dashboard/instructor/assessments">✓ Grade Assessments</Link><Link href="/dashboard/instructor/calendar">▦ View My Calendar</Link><Link href="/dashboard/instructor/messages">✉ Message Students</Link></aside></div></section>
}
function InstructorInterior({section,paths,notify}:{section:string;paths:Pathway[];notify:(m:string)=>void}){
 const titles:Record<string,string>={courses:"My Courses",cohorts:"My Cohorts",students:"Students",assessments:"Assessments",resources:"Resources",calendar:"Calendar",messages:"Messages",support:"Support",reports:"Reports",settings:"Settings"};
 const items=paths.map((p,i)=>({title:p.title,subtitle:`${p.code} · ${p.moduleCount} modules`,status:i<3?"Active":"Draft",metric:`${8+i*2} learners`}));
 return <section className="institution-interior"><header className="institution-interior-title"><div><small>INSTRUCTOR WORKSPACE</small><h1>{titles[section]||"Workspace"}</h1><p>Assigned access within the organization’s governed curriculum and learner records.</p></div><button onClick={()=>notify("Instructor action recorded")}>＋ New Action</button></header>
 {section==="courses"&&<InstructorCards items={items}/>}
 {section==="cohorts"&&<SimpleInstructorTable headings={["Cohort","Course","Learners","Schedule","Status"]} rows={paths.map((p,i)=>[`Cohort ${String.fromCharCode(65+i)}`,p.code,String(8+i*2),`${i%2?"Tue/Thu":"Mon/Wed"} ${9+i}:00`,"Active"])}/>}
 {section==="students"&&<SimpleInstructorTable headings={["Learner","Assigned Course","Progress","Evidence Queue","Status"]} rows={[["Emily Carter",paths[0]?.code||"PDG","72%","1","On Track"],["Marcus Johnson",paths[1]?.code||"PDT","54%","2","At Risk"],["Sophie Martinez",paths[2]?.code||"CAT","83%","0","On Track"],["Daniel Kim",paths[3]?.code||"CPP","100%","0","Complete"]]}/>}
 {section==="assessments"&&<SimpleInstructorTable headings={["Assessment","Course","Submissions","Human Review","Due"]} rows={paths.map((p,i)=>[`${p.code} Applied Evidence`,p.code,`${8+i}/12`,i%2?"Required":"Audit only",`Sep ${14+i}`])}/>}
 {section==="resources"&&<div className="institution-card institution-list-page"><nav><label className="upload-button">↑ Upload Resource<input hidden type="file" onChange={e=>e.target.files?.[0]&&notify(`${e.target.files[0].name} uploaded`)}/></label><button>Approved</button><button>My Uploads</button></nav><SimpleInstructorTable headings={["Resource","Type","Course","Approval","Updated"]} rows={paths.map((p,i)=>[`${p.code} Instructor Guide`,"Document",p.code,"Approved",`Sep ${10+i}`])}/></div>}
 {section==="calendar"&&<div className="institution-card instructor-calendar">{Array.from({length:28},(_,i)=><div key={i}><b>{i+1}</b>{[2,5,8,12,16,20,24].includes(i)&&<span>{paths[i%paths.length]?.code} Session</span>}</div>)}</div>}
 {section==="messages"&&<InstructorMessages/>}
 {section==="support"&&<div className="meeting-grid">{[["♡","Academic Support"],["♙","Learner Escalation"],["⬡","Safety & Conduct"],["▰","Platform Help"]].map(([icon,title])=><button className="institution-card" key={title} onClick={()=>notify(`${title} opened`)}><span>{icon}</span><h2>{title}</h2><p>Access governed support workflows and escalation history.</p></button>)}</div>}
 {section==="reports"&&<div className="report-grid">{paths.map((p,i)=><article className="institution-card" key={p.code}><h2>{p.code}</h2><strong className="big-number">{78-i*8}%</strong><p>Learner completion</p><progress max="100" value={78-i*8}/></article>)}</div>}
 {section==="settings"&&<div className="settings-grid"><section className="institution-card settings-form"><h2>Instructor Profile</h2><label>Display Name<input defaultValue="Jamie Carter"/></label><label>Primary Role<input defaultValue="Curriculum Instructor"/></label><label>Organization<input defaultValue={orgNameSafe()}/></label><button onClick={()=>notify("Instructor settings saved")}>Save Changes</button></section><aside className="institution-card"><h2>Notifications</h2>{["Assessment submissions","Learner risk alerts","Meeting reminders","Curriculum updates"].map(x=><label className="toggle-row" key={x}>{x}<input type="checkbox" defaultChecked/></label>)}</aside></div>}
 </section>
}
function InstructorCards({items}:{items:Array<{title:string;subtitle:string;status:string;metric:string}>}){return <div className="instructor-course-grid">{items.map((x,i)=><article className="institution-card" key={x.title}><img src={["/leashed-assets/program-groomer.webp","/leashed-assets/program-business.webp","/leashed-assets/program-cat.webp","/leashed-assets/program-sitter.webp"][i]} alt=""/><h2>{x.title}</h2><p>{x.subtitle}</p><span>{x.status}</span><b>{x.metric}</b><Link href="/dashboard/instructor/students">Open assigned course →</Link></article>)}</div>}
function SimpleInstructorTable({headings,rows}:{headings:string[];rows:string[][]}){return <div className="institution-card generic-table-wrap"><div className="generic-table"><div className="generic-table-head">{headings.map(h=><span key={h}>{h}</span>)}</div>{rows.map((row,i)=><button key={i} style={{gridTemplateColumns:`repeat(${headings.length},minmax(100px,1fr))`}}>{row.map((cell,j)=><span key={j}>{j===0?<strong>{cell}</strong>:cell}</span>)}</button>)}</div></div>}
function InstructorMessages(){const [value,setValue]=useState("");const [messages,setMessages]=useState(["Sarah Lopez: I have a question about the evidence rubric.","Marcus Johnson: My assignment upload is complete."]);return <div className="institution-messages"><aside className="institution-card">{["All Students","Cohort A","Cohort B","Instructor Team","Organization Admin"].map(x=><button key={x}>{x}<small>Conversation</small></button>)}</aside><section className="institution-card"><header><h2>Assigned Learners</h2></header><div>{messages.map(x=><p key={x}>{x}</p>)}</div><footer><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Type a message…"/><button onClick={()=>{if(value){setMessages([...messages,`You: ${value}`]);setValue("")}}}>➤</button></footer></section></div>}
function orgNameSafe(){if(typeof window==="undefined")return"Leashed Demonstration School";try{return JSON.parse(localStorage.getItem("leashed_onboarding_organization")||"{}").organizationName||"Leashed Demonstration School"}catch{return"Leashed Demonstration School"}}